<script setup>
import {reactive, onMounted, useTemplateRef, ref} from "vue"

const state = reactive({
  imgpaths: [
    "Switzerland____bollard_591.jpg",
    "Ukraine____bollard_367.jpg",
    "Mongolia____bollard_63.jpg",
    "Canada____bollard_194.jpg",
    "United States____bollard_448.jpg",
    "United States____bollard_474.jpg",
    "France____bollard_337.jpg",
    "United States____bollard_460.jpg",
    "Ecuador____bollard_224.jpg",
    "Italy____bollard_406.jpg",
    "Malaysia____bollard_359.jpg",
    "Faroe Islands____bollard_118.jpg",
    "Canada____bollard_547.jpg",
    "Germany____bollard_391.jpg",
    "France____bollard_121.jpg",
    "France____bollard_120.jpg",
    "Ireland____bollard_506.jpg",
    "Ecuador____bollard_225.jpg",
    "United States____bollard_461.jpg",
    "United States____bollard_475.jpg",
    "Iceland____bollard_129.jpg",
    "Austria____bollard_679.jpg",
    "Brazil____bollard_264.jpg",
    "Russia____bollard_87.jpg",
    "Portugal____bollard_157.jpg",
    "Cambodia____bollard_82.jpg",
    "Sweden____bollard_187.jpg",
    "Switzerland____bollard_590.jpg",
    "Croatia____bollard_499.jpg",
    "Portugal____bollard_155.jpg",
    "Kenya____bollard_695.jpg",
    "Czech Republic____bollard_113.jpg",
    "Uganda____bollard_363.jpg",
    "Bulgaria____bollard_109.jpg",
    "United Kingdom (Scotland)____bollard_680.jpg",
    "Canada____bollard_183.jpg",
    "United Kingdom (Belfast)____bollard_538.jpg",
    "Poland____bollard_610.jpg",
    "United States____bollard_463.jpg",
    "United States____bollard_477.jpg",
    "Bhutan____bollard_623.jpg",
    "Senegal____bollard_13.jpg",
    "Ecuador____bollard_227.jpg",
    "Ecuador____bollard_569.jpg",
    "Ireland____bollard_504.jpg",
    "France____bollard_122.jpg",
    "Netherlands____bollard_439.jpg",
    "Japan____bollard_96.jpg",
    "Greece____bollard_402.jpg",
    "Slovenia____bollard_168.jpg",
    "Ireland____bollard_505.jpg",
    "Ecuador____bollard_226.jpg",
    "Netherlands____bollard_148.jpg",
    "United States____bollard_476.jpg",
    "United States____bollard_462.jpg",
    "United Kingdom____bollard_507.jpg",
    "Serbia____bollard_163.jpg",
    "Canada____bollard_182.jpg",
    "Hungary____bollard_128.jpg",
    "Hungary____bollard_316.jpg",
    "Thailand____bollard_702.jpg",
    "Australia____bollard_275.jpg",
    "Austria____bollard_487.jpg",
    "Ireland____bollard_449.jpg",
    "United Kingdom____bollard_649.jpg",
    "Canada____bollard_192.jpg",
    "Canada____bollard_186.jpg",
    "United States____bollard_248.jpg",
    "Laos____bollard_691.jpg",
    "United States____bollard_466.jpg",
    "United States____bollard_472.jpg",
    "Peru____bollard_229.jpg",
    "Senegal____bollard_16.jpg",
    "Japan____bollard_51.jpg",
    "Ecuador____bollard_222.jpg",
    "Croatia____bollard_265.jpg",
    "Spain____bollard_340.jpg",
    "Spain____bollard_426.jpg",
    "Spain____bollard_341.jpg",
    "Austria____bollard_535.jpg",
    "Austria____bollard_284.jpg",
    "Ecuador____bollard_223.jpg",
    "Japan____bollard_50.jpg",
    "Peru____bollard_228.jpg",
    "United States____bollard_473.jpg",
    "Slovenia____bollard_390.jpg",
    "Mexico____bollard_401.jpg",
    "Turkey____bollard_247.jpg",
    "United States____bollard_261.jpg",
    "Croatia____bollard_112.jpg",
    "Canada____bollard_193.jpg",
    "United Kingdom____bollard_648.jpg",
    "Isle of Man____bollard_133.jpg",
    "Cocos Islands (Australia)____bollard_357.jpg",
    "Australia____bollard_528.jpg",
    "Mexico____bollard_198.jpg",
    "Australia____bollard_500.jpg",
    "Kenya____bollard_320.jpg",
    "Bolivia____bollard_345.jpg",
    "Austria____bollard_682.jpg",
    "Chile____bollard_400.jpg",
    "Canada____bollard_185.jpg",
    "Belarus____bollard_559.jpg",
    "United States____bollard_277.jpg",
    "Canada____bollard_191.jpg",
    "Iceland____bollard_677.jpg",
    "Mexico____bollard_371.jpg",
    "France____bollard_497.jpg",
    "Serbia____bollard_164.jpg",
    "North Macedonia____bollard_149.jpg",
    "United States____bollard_471.jpg",
    "Spain____bollard_169.jpg",
    "United States____bollard_465.jpg",
    "United States____bollard_459.jpg",
    "Spain____bollard_627.jpg",
    "Ireland____bollard_502.jpg",
    "Ecuador____bollard_221.jpg",
    "Senegal____bollard_15.jpg",
    "Albania____bollard_97.jpg",
    "Austria____bollard_523.jpg",
    "Austria____bollard_537.jpg",
    "Spain____bollard_342.jpg",
    "Austria____bollard_536.jpg",
    "France____bollard_125.jpg",
    "United States____bollard_699.jpg",
    "Japan____bollard_47.jpg",
    "Ireland____bollard_503.jpg",
    "United Kingdom____bollard_501.jpg",
    "United States____bollard_458.jpg",
    "United Kingdom____bollard_267.jpg",
    "Tunisia____bollard_306.jpg",
    "United States____bollard_464.jpg",
    "United States____bollard_470.jpg",
    "Serbia____bollard_165.jpg",
    "Hungary____bollard_700.jpg",
    "New Zealand____bollard_301.jpg",
    "Canada____bollard_190.jpg",
    "Canada____bollard_184.jpg",
    "Taiwan____bollard_90.jpg",
    "Belgium____bollard_608.jpg",
    "Liechtenstein____bollard_438.jpg",
    "Netherlands____bollard_562.jpg",
    "Czech Republic____bollard_114.jpg",
    "Japan____bollard_567.jpg",
    "Andorra____bollard_99.jpg",
    "Australia____bollard_214.jpg",
    "England (UK)____bollard_452.jpg",
    "Russia____bollard_433.jpg",
    "Lithuania____bollard_687.jpg",
    "North Macedonia____bollard_701.jpg",
    "South Korea____bollard_80.jpg",
    "United States____bollard_205.jpg",
    "United States____bollard_211.jpg",
    "Bhutan____bollard_333.jpg",
    "land (Finland)____bollard_235.jpg",
    "Japan____bollard_662.jpg",
    "Norway____bollard_618.jpg",
    "Netherlands____bollard_667.jpg",
    "Finland____bollard_673.jpg",
    "Australia____bollard_374.jpg",
    "Australia____bollard_412.jpg",
    "Canada____bollard_524.jpg",
    "Austria____bollard_550.jpg",
    "Spain____bollard_324.jpg",
    "Lithuania____bollard_269.jpg",
    "Canada____bollard_525.jpg",
    "Australia____bollard_375.jpg",
    "United States____bollard_199.jpg",
    "Australia____bollard_413.jpg",
    "Austria____bollard_587.jpg",
    "Australia____bollard_407.jpg",
    "Jersey____bollard_136.jpg",
    "Slovakia____bollard_586.jpg",
    "Slovakia____bollard_592.jpg",
    "Netherlands____bollard_666.jpg",
    "United Kingdom____bollard_598.jpg",
    "Germany____bollard_126.jpg",
    "United States____bollard_210.jpg",
    "Colombia____bollard_291.jpg",
    "United States____bollard_204.jpg",
    "Austria____bollard_626.jpg",
    "Czech Republic____bollard_364.jpg",
    "Belgium____bollard_108.jpg",
    "South Korea____bollard_81.jpg",
    "England (UK)____bollard_453.jpg",
    "Malaysia____bollard_59.jpg",
    "Austria____bollard_418.jpg",
    "Cambodia____bollard_361.jpg",
    "Tunisia____bollard_18.jpg",
    "Japan____bollard_515.jpg",
    "Australia____bollard_215.jpg",
    "Austria____bollard_383.jpg",
    "Australia____bollard_217.jpg",
    "South Korea____bollard_83.jpg",
    "Indonesia____bollard_38.jpg",
    "Slovenia____bollard_297.jpg",
    "United States____bollard_212.jpg",
    "United States____bollard_206.jpg",
    "United States____bollard_560.jpg",
    "Andorra____bollard_326.jpg",
    "Australia____bollard_411.jpg",
    "Runion (France)____bollard_350.jpg",
    "Romania____bollard_160.jpg",
    "Latvia____bollard_137.jpg",
    "Romania____bollard_175.jpg",
    "Montenegro____bollard_143.jpg",
    "Austria____bollard_553.jpg",
    "Albania____bollard_245.jpg",
    "Canada____bollard_526.jpg",
    "Austria____bollard_584.jpg",
    "Australia____bollard_410.jpg",
    "France____bollard_424.jpg",
    "Netherlands____bollard_665.jpg",
    "Kenya____bollard_556.jpg",
    "England (UK)____bollard_256.jpg",
    "United States____bollard_207.jpg",
    "Argentina____bollard_243.jpg",
    "United States____bollard_213.jpg",
    "Singapore____bollard_554.jpg",
    "Ecuador____bollard_669.jpg",
    "Indonesia____bollard_39.jpg",
    "Brazil____bollard_576.jpg",
    "Austria____bollard_427.jpg",
    "Japan____bollard_516.jpg",
    "Australia____bollard_216.jpg",
    "Austria____bollard_382.jpg",
    "Australia____bollard_548.jpg",
    "Ghana____bollard_659.jpg",
    "Austria____bollard_386.jpg",
    "Spain____bollard_294.jpg",
    "Belgium____bollard_325.jpg",
    "Bulgaria____bollard_379.jpg",
    "Austria____bollard_392.jpg",
    "Chile____bollard_676.jpg",
    "Finland____bollard_271.jpg",
    "Croatia____bollard_372.jpg",
    "Cambodia____bollard_31.jpg",
    "Malaysia____bollard_62.jpg",
    "Sweden____bollard_493.jpg",
    "Ireland____bollard_600.jpg",
    "Portugal____bollard_494.jpg",
    "Isle of Man____bollard_421.jpg",
    "United States____bollard_565.jpg",
    "United States____bollard_203.jpg",
    "Bermuda____bollard_513.jpg",
    "South Korea____bollard_79.jpg",
    "Kyrgyzstan____bollard_561.jpg",
    "Malaysia____bollard_328.jpg",
    "Canada____bollard_250.jpg",
    "Germany____bollard_486.jpg",
    "Argentina____bollard_642.jpg",
    "Australia____bollard_373.jpg",
    "Australia____bollard_415.jpg",
    "Austria____bollard_595.jpg",
    "New Zealand____bollard_611.jpg",
    "Romania____bollard_428.jpg",
    "United Kingdom____bollard_549.jpg",
    "Jersey____bollard_332.jpg",
    "Australia____bollard_617.jpg",
    "Sweden____bollard_280.jpg",
    "Uganda____bollard_35.jpg",
    "South Korea____bollard_78.jpg",
    "United States____bollard_564.jpg",
    "France____bollard_541.jpg",
    "United States____bollard_202.jpg",
    "Sweden____bollard_492.jpg",
    "Cambodia____bollard_30.jpg",
    "Bulgaria____bollard_378.jpg",
    "Austria____bollard_393.jpg",
    "Austria____bollard_387.jpg",
    "Ghana____bollard_658.jpg",
    "Austria____bollard_385.jpg",
    "Cambodia____bollard_32.jpg",
    "Australia____bollard_588.jpg",
    "Spain____bollard_268.jpg",
    "Austria____bollard_434.jpg",
    "Sweden____bollard_490.jpg",
    "United States____bollard_200.jpg",
    "United States____bollard_566.jpg",
    "Bangladesh____bollard_645.jpg",
    "Norway____bollard_153.jpg",
    "Poland____bollard_675.jpg",
    "Japan____bollard_303.jpg",
    "Australia____bollard_403.jpg",
    "Uruguay____bollard_231.jpg",
    "Austria____bollard_568.jpg",
    "Montenegro____bollard_144.jpg",
    "Greece____bollard_300.jpg",
    "Montenegro____bollard_145.jpg",
    "Spain____bollard_309.jpg",
    "Belgium____bollard_521.jpg",
    "New Zealand____bollard_612.jpg",
    "Canada____bollard_520.jpg",
    "Laos____bollard_67.jpg",
    "Uganda____bollard_36.jpg",
    "Andorra____bollard_282.jpg",
    "United States____bollard_201.jpg",
    "United Kingdom____bollard_358.jpg",
    "South Korea____bollard_84.jpg",
    "Sweden____bollard_491.jpg",
    "Canada____bollard_656.jpg",
    "Malaysia____bollard_60.jpg",
    "Spain____bollard_255.jpg",
    "Albania____bollard_323.jpg",
    "Cambodia____bollard_27.jpg",
    "Australia____bollard_589.jpg",
    "Spain____bollard_296.jpg",
    "Chile____bollard_660.jpg",
    "Germany____bollard_527.jpg",
    "Netherlands____bollard_295.jpg",
    "Peru____bollard_319.jpg",
    "Indonesia____bollard_254.jpg",
    "United Kingdom____bollard_619.jpg",
    "Austria____bollard_606.jpg",
    "Italy____bollard_134.jpg",
    "Malaysia____bollard_694.jpg",
    "India____bollard_579.jpg",
    "Turkey____bollard_362.jpg",
    "Ecuador____bollard_514.jpg",
    "Australia____bollard_355.jpg",
    "Monaco____bollard_425.jpg",
    "Qatar____bollard_663.jpg",
    "Ireland____bollard_545.jpg",
    "Japan____bollard_441.jpg",
    "Bangladesh____bollard_19.jpg",
    "Australia____bollard_396.jpg",
    "United Arab Emirates____bollard_674.jpg",
    "Australia____bollard_354.jpg",
    "India____bollard_544.jpg",
    "Greece____bollard_127.jpg",
    "Italy____bollard_135.jpg",
    "Kyrgyzstan____bollard_56.jpg",
    "Netherlands____bollard_684.jpg",
    "Bhutan____bollard_25.jpg",
    "South Korea____bollard_77.jpg",
    "Denmark____bollard_376.jpg",
    "Austria____bollard_613.jpg",
    "Sweden____bollard_489.jpg",
    "Kenya____bollard_414.jpg",
    "Singapore____bollard_76.jpg",
    "Bulgaria____bollard_377.jpg",
    "Peru____bollard_318.jpg",
    "Austria____bollard_388.jpg",
    "United Kingdom____bollard_181.jpg",
    "Estonia____bollard_116.jpg",
    "Cambodia____bollard_29.jpg",
    "New Zealand____bollard_218.jpg",
    "Jersey____bollard_511.jpg",
    "Austria____bollard_605.jpg",
    "South Africa____bollard_237.jpg",
    "Monaco____bollard_142.jpg",
    "Sweden____bollard_299.jpg",
    "Laos____bollard_69.jpg",
    "Kyrgyzstan____bollard_54.jpg",
    "Argentina____bollard_317.jpg",
    "Italy____bollard_692.jpg",
    "Sweden____bollard_272.jpg",
    "Australia____bollard_430.jpg",
    "Australia____bollard_356.jpg",
    "Switzerland____bollard_498.jpg",
    "Australia____bollard_395.jpg",
    "Australia____bollard_381.jpg",
    "Turkey____bollard_177.jpg",
    "Turkey____bollard_176.jpg",
    "Australia____bollard_380.jpg",
    "Greece____bollard_440.jpg",
    "New Zealand____bollard_609.jpg",
    "Australia____bollard_431.jpg",
    "Sweden____bollard_273.jpg",
    "Botswana____bollard_542.jpg",
    "Italy____bollard_693.jpg",
    "Singapore____bollard_429.jpg",
    "United Kingdom____bollard_551.jpg",
    "Kyrgyzstan____bollard_55.jpg",
    "Japan____bollard_641.jpg",
    "Laos____bollard_68.jpg",
    "Sweden____bollard_298.jpg",
    "Philippines____bollard_574.jpg",
    "Gibraltar____bollard_510.jpg",
    "Peru____bollard_657.jpg",
    "Japan____bollard_292.jpg",
    "Cambodia____bollard_28.jpg",
    "Estonia____bollard_117.jpg",
    "Indonesia____bollard_252.jpg",
    "Slovakia____bollard_167.jpg",
    "Slovakia____bollard_629.jpg",
    "Netherlands____bollard_522.jpg",
    "Portugal____bollard_338.jpg",
    "Belgium____bollard_106.jpg",
    "Indonesia____bollard_34.jpg",
    "Bhutan____bollard_22.jpg",
    "Lithuania____bollard_139.jpg",
    "United Kingdom____bollard_596.jpg",
    "Hong Kong____bollard_423.jpg",
    "Brazil____bollard_625.jpg",
    "India____bollard_543.jpg",
    "Australia____bollard_409.jpg",
    "Australia____bollard_353.jpg",
    "Canada____bollard_259.jpg",
    "Andorra____bollard_100.jpg",
    "Runion (France)____bollard_348.jpg",
    "United States____bollard_632.jpg",
    "Netherlands____bollard_331.jpg",
    "Brazil____bollard_368.jpg",
    "France____bollard_616.jpg",
    "Andorra____bollard_101.jpg",
    "Australia____bollard_352.jpg",
    "Australia____bollard_408.jpg",
    "Kenya____bollard_8.jpg",
    "Hong Kong____bollard_422.jpg",
    "Nigeria____bollard_557.jpg",
    "United Kingdom____bollard_597.jpg",
    "Czech Republic____bollard_343.jpg",
    "Bhutan____bollard_23.jpg",
    "Belgium____bollard_107.jpg",
    "Malaysia____bollard_283.jpg",
    "Ukraine____bollard_336.jpg",
    "Spain____bollard_263.jpg",
    "Italy____bollard_279.jpg",
    "Slovakia____bollard_628.jpg",
    "Ecuador____bollard_329.jpg",
    "Slovakia____bollard_166.jpg",
    "Japan____bollard_530.jpg",
    "Reunion (France)____bollard_517.jpg",
    "Bolivia____bollard_688.jpg",
    "Sweden____bollard_670.jpg",
    "Belgium____bollard_105.jpg",
    "United States____bollard_209.jpg",
    "Argentina____bollard_305.jpg",
    "Slovenia____bollard_313.jpg",
    "Finland____bollard_119.jpg",
    "Lebanon____bollard_417.jpg",
    "Bangladesh____bollard_20.jpg",
    "United States____bollard_631.jpg",
    "Latvia____bollard_138.jpg",
    "United States____bollard_630.jpg",
    "Australia____bollard_351.jpg",
    "Andorra____bollard_102.jpg",
    "Lebanon____bollard_416.jpg",
    "New Zealand____bollard_394.jpg",
    "Northern Ireland, England (UK)____bollard_236.jpg",
    "Kyrgyzstan____bollard_53.jpg",
    "United States____bollard_208.jpg",
    "Lesotho____bollard_639.jpg",
    "Austria____bollard_366.jpg",
    "Ukraine____bollard_335.jpg",
    "Spain____bollard_260.jpg",
    "Luxembourg____bollard_327.jpg",
    "Austria____bollard_399.jpg",
    "Japan____bollard_531.jpg",
    "Norway____bollard_289.jpg",
    "Lebanon____bollard_539.jpg",
    "Czech Republic____bollard_643.jpg",
    "United Kingdom____bollard_652.jpg",
    "Cambodia____bollard_322.jpg",
    "Canada____bollard_638.jpg",
    "Indonesia____bollard_45.jpg",
    "Taiwan____bollard_89.jpg",
    "United States____bollard_290.jpg",
    "Botswana____bollard_2.jpg",
    "Denmark____bollard_314.jpg",
    "Austria____bollard_103.jpg",
    "Canada____bollard_189.jpg",
    "Ukraine____bollard_178.jpg",
    "Australia____bollard_646.jpg",
    "Bolivia____bollard_573.jpg",
    "United States____bollard_496.jpg",
    "United States____bollard_482.jpg",
    "North Macedonia____bollard_151.jpg",
    "United States____bollard_469.jpg",
    "Poland____bollard_154.jpg",
    "Thailand____bollard_91.jpg",
    "United States____bollard_455.jpg",
    "France____bollard_302.jpg",
    "Italy____bollard_369.jpg",
    "United Arab Emirates____bollard_603.jpg",
    "Ecuador (Galpagos)____bollard_668.jpg",
    "India____bollard_533.jpg",
    "United States____bollard_454.jpg",
    "Spain____bollard_170.jpg",
    "United Kingdom____bollard_257.jpg",
    "United States____bollard_468.jpg",
    "United States____bollard_483.jpg",
    "North Macedonia____bollard_150.jpg",
    "Germany____bollard_602.jpg",
    "Italy____bollard_624.jpg",
    "Bolivia____bollard_572.jpg",
    "Ukraine____bollard_179.jpg",
    "Denmark____bollard_467.jpg",
    "Canada____bollard_188.jpg",
    "Denmark____bollard_315.jpg",
    "United States____bollard_285.jpg",
    "Taiwan____bollard_88.jpg",
    "Jordan____bollard_52.jpg",
    "Hungary____bollard_678.jpg",
    "Liechtenstein____bollard_420.jpg",
    "Sweden____bollard_171.jpg",
    "Japan____bollard_580.jpg",
    "Hungary____bollard_485.jpg",
    "United Kingdom____bollard_653.jpg",
    "United Kingdom____bollard_647.jpg",
    "Christmas Island____bollard_233.jpg",
    "Australia____bollard_519.jpg",
    "Ireland____bollard_447.jpg",
    "Norway____bollard_288.jpg",
    "Netherlands____bollard_585.jpg",
    "Mexico____bollard_197.jpg",
    "Senegal____bollard_681.jpg",
    "Italy____bollard_578.jpg",
    "Russia____bollard_73.jpg",
    "Japan____bollard_555.jpg",
    "Philippines____bollard_70.jpg",
    "United Kingdom____bollard_651.jpg",
    "Israel____bollard_43.jpg",
    "Denmark____bollard_115.jpg",
    "Canada____bollard_607.jpg",
    "Ireland____bollard_690.jpg",
    "Luxembourg____bollard_141.jpg",
    "Slovenia____bollard_389.jpg",
    "San Marino____bollard_162.jpg",
    "Bolivia____bollard_570.jpg",
    "North Macedonia____bollard_152.jpg",
    "United States____bollard_481.jpg",
    "United States____bollard_495.jpg",
    "Switzerland____bollard_174.jpg",
    "United States____bollard_442.jpg",
    "Isle of Man____bollard_512.jpg",
    "United States____bollard_456.jpg",
    "South Africa____bollard_334.jpg",
    "Slovenia____bollard_404.jpg",
    "Japan____bollard_49.jpg",
    "Austria____bollard_276.jpg",
    "Albania____bollard_98.jpg",
    "Austria____bollard_262.jpg",
    "Poland____bollard_432.jpg",
    "Japan____bollard_48.jpg",
    "Peru____bollard_230.jpg",
    "United States____bollard_457.jpg",
    "Slovenia____bollard_405.jpg",
    "United States____bollard_443.jpg",
    "Netherlands____bollard_633.jpg",
    "Thailand____bollard_93.jpg",
    "Germany____bollard_601.jpg",
    "United States____bollard_480.jpg",
    "Bolivia____bollard_571.jpg",
    "Luxembourg____bollard_140.jpg",
    "United States____bollard_286.jpg",
    "United Kingdom____bollard_644.jpg",
    "Spain____bollard_577.jpg",
    "United Kingdom____bollard_650.jpg",
    "Poland____bollard_546.jpg",
    "Russia____bollard_72.jpg",
    "Ghana____bollard_637.jpg",
    "Mexico____bollard_196.jpg",
    "Kenya____bollard_672.jpg",
    "Netherlands____bollard_582.jpg",
    "Norway____bollard_270.jpg",
    "Sweden____bollard_604.jpg",
    "United Kingdom____bollard_654.jpg",
    "Czech Republic____bollard_123.jpg",
    "Australia____bollard_293.jpg",
    "Christmas Island____bollard_234.jpg",
    "Israel____bollard_46.jpg",
    "Ireland____bollard_130.jpg",
    "Cambodia____bollard_683.jpg",
    "Greenland____bollard_195.jpg",
    "Malta____bollard_697.jpg",
    "Slovakia____bollard_266.jpg",
    "United States____bollard_484.jpg",
    "Sweden____bollard_599.jpg",
    "United Kingdom____bollard_278.jpg",
    "India____bollard_534.jpg",
    "United States____bollard_686.jpg",
    "Australia____bollard_330.jpg",
    "Austria____bollard_529.jpg",
    "Italy____bollard_384.jpg",
    "Poland____bollard_436.jpg",
    "Poland____bollard_437.jpg",
    "Netherlands____bollard_636.jpg",
    "United States____bollard_446.jpg",
    "Chile____bollard_219.jpg",
    "Italy____bollard_622.jpg",
    "Austria____bollard_104.jpg",
    "Indonesia____bollard_42.jpg",
    "Ukraine____bollard_180.jpg",
    "Ireland____bollard_131.jpg",
    "Bulgaria____bollard_110.jpg",
    "United Kingdom____bollard_655.jpg",
    "Kenya____bollard_698.jpg",
    "Portugal____bollard_158.jpg",
    "Sri Lanka____bollard_552.jpg",
    "Netherlands____bollard_583.jpg",
    "Italy____bollard_540.jpg",
    "Canada____bollard_365.jpg",
    "Netherlands____bollard_581.jpg",
    "Russia____bollard_75.jpg",
    "Kenya____bollard_671.jpg",
    "Rwanda____bollard_615.jpg",
    "United States____bollard_281.jpg",
    "New Zealand____bollard_241.jpg",
    "Indonesia____bollard_40.jpg",
    "Ireland____bollard_696.jpg",
    "United States____bollard_518.jpg",
    "United States____bollard_450.jpg",
    "United Kingdom____bollard_509.jpg",
    "United States____bollard_444.jpg",
    "France____bollard_307.jpg",
    "Czech Republic____bollard_242.jpg",
    "Netherlands____bollard_634.jpg",
    "Thailand____bollard_94.jpg",
    "Switzerland____bollard_172.jpg",
    "Netherlands____bollard_620.jpg",
    "Netherlands____bollard_146.jpg",
    "United States____bollard_478.jpg",
    "United States____bollard_685.jpg",
    "Poland____bollard_435.jpg",
    "San Marino____bollard_398.jpg",
    "Greenland____bollard_593.jpg",
    "Switzerland____bollard_173.jpg",
    "Thailand____bollard_95.jpg",
    "Kyrgyzstan____bollard_253.jpg",
    "United States____bollard_479.jpg",
    "Netherlands____bollard_147.jpg",
    "United States____bollard_445.jpg",
    "United States____bollard_451.jpg",
    "United Kingdom____bollard_508.jpg",
    "Ghana____bollard_7.jpg",
    "Italy____bollard_621.jpg",
    "Austria____bollard_661.jpg",
    "Indonesia____bollard_41.jpg",
    "Liechtenstein____bollard_419.jpg",
    "Ireland____bollard_132.jpg",
    "Switzerland____bollard_563.jpg",
    "Israel____bollard_44.jpg",
    "Rwanda____bollard_614.jpg",
    "Russia____bollard_74.jpg",
    "Bangladesh____bollard_558.jpg",
    "Austria____bollard_488.jpg",
  ],
  countries: null,
  img: "",
  country: "",
  numOptions: 4,
  options: [],
  buttonStates: [null, null, null, null, null, null, null, null, null]
})

function setCountries() {
  const ls = []
  for (let path of state.imgpaths) {
    const country = path.split("____")[0]
    if (!ls.includes(country)) ls.push(country)
  }
  state.countries = ls
}

function setQuestion() {
  state.img = state.imgpaths[Math.floor(Math.random()*state.imgpaths.length)];
  state.country = state.img.split("____")[0]

  let options = [state.country]
  while (options.length < state.numOptions) {
    let country = state.countries[Math.floor(Math.random()*state.countries.length)];
    if (!options.includes(country)) options.push(country)
  }

  let n = Math.floor(Math.random()*state.numOptions)
  state.options = [...options.slice(n), ...options.slice(0, n)]
}

const buttons = {}
for (let i=0; i<state.numOptions; i++) {
  buttons[i] = ref(`button${i}`)
}

function handleButtonClick(option, i) {
  if (option == state.country) state.buttonStates[i] = "correct"
  else state.buttonStates[i] = "wrong"
}

function getButtonClass(i) {
  let cls = "btn btn-lg"
  if (state.buttonStates[i] == null) cls += " btn-secondary"
  else if (state.buttonStates[i] == "wrong") cls += " btn-danger"
  else if (state.buttonStates[i] == "correct") cls += " btn-success"
  return cls
}

function reset() {
  state.buttonStates = [null, null, null, null, null, null, null, null, null]
  setQuestion()
}

onMounted(() => {
  setCountries()
  setQuestion()
})

</script>

<template>
  <main>
    <div class="container">

      <h1>Bollards!!</h1><br>

      <div class="question">

        <img :src="'images128/'+state.img" class="main-img"
          @click="reset()"
          />

        <div class="d-grid d-md-block">
          <button v-for="[i, option] of Object.entries(state.options)" 
            :class="getButtonClass(i)"
            @click="handleButtonClick(option, i)"
            :ref="`button${i}`">
            {{ option }}
          </button>
        </div>

      </div>

      <div class="score">

      </div>


    </div>
  </main>
</template>

<style>

.container {
  padding: 1em 2em 1em 2em;
  max-width: 600px;
}

.btn {
  margin-top: 0.75em
}

.main-img {
  width: 100%
}

</style>